### ISSUE TITLE
Should list files that included by prefixing "!" in .gitignore

### ISSUE THREAD

**Issue by chrisyip** [atom/fuzzy-finder#101]
Please take a look at this screenshot:

![atom](https://cloud.githubusercontent.com/assets/189559/7510907/750bfd5a-f4d3-11e4-8a36-891e7a3cdb77.png)

In my case, I need to add a `default` configuration in `config/`, and my colleagues can put their own configuration inside `config/` that won't be committed by accident. But after doing this, I can't use `CMD + T` to open any files under `config/`.

**Comment by thomasjo** [comment]
You've excluded the folder, hence it doesn't matter that you negate the exclusion for certain files. You need to change `config/` to `config/*` to specifically exclude the contents of the folder, not the folder itself.

See the [official documentation](http://git-scm.com/docs/gitignore) for more details.

**Comment by chrisyip** [comment]
![atom](https://cloud.githubusercontent.com/assets/189559/7514968/34681622-f4f5-11e4-9747-722ee28de8fc.png)

@thomasjo fuzzy finder still not working.

**Comment by thomasjo** [comment]
Thanks for the update. I just tried, and I managed to repro. This issue is actually a duplicate of https://github.com/atom/fuzzy-finder/issues/65. Please subscribe to that issue for updates :bow:
