### ISSUE TITLE
Setting To Open Permanently When Using Preview Tabs

### ISSUE THREAD

**Issue by eviljoe** [atom/fuzzy-finder#108]
There should be a setting to open selected files permanently when using the preview tabs feature from the [atom/tabs](https://github.com/atom/tabs) package.

**Comment by mehcode** [comment]
I disagree. However there should be a key combination to open the file selected permanently (`Ctrl-Enter` or `Shift-Enter`; whatever sublime did). We should also auto open files in preview mode as they are selected with the fuzzy finder.

**Comment by eviljoe** [comment]
As long as I can remap the "open permanently" action in the keymap to `Enter`, I would be happy with that solution.

**Comment by LucioFranco** [comment]
+1 Would like to see something like this

**Comment by benogle** [comment]
This is fixed on master and the 1.5.x line which is in beta now. See https://github.com/atom/atom/issues/9165 for more information.
