### ISSUE TITLE
Highlight matched substring in results

### ISSUE THREAD

**Issue by DouweM** [atom/fuzzy-finder#11]
Like in SublimeText:
![](http://cdn.tutsplus.com/net/uploads/legacy/1038_sublime/activate.slim.jpg)

This would also be useful in https://github.com/atom/command-palette.

**Comment by mnquintana** [comment]
This should be implemented in [atom/atom-space-pen-views](https://github.com/atom/atom-space-pen-views) for `SelectListView` so the Command Palette can also take advantage of this.

**Comment by izuzak** [comment]
> This should be implemented in atom/atom-space-pen-views for SelectListView so the Command Palette can also take advantage of this.

I'm not sure that should be the case (or that it's easily doable). Notice that the SelectListView is populated with HTML generated completely by subclases:

https://github.com/atom/atom-space-pen-views/blob/0e5fc262cc62d453bbd6dce9ecaec5caddc553f9/src/select-list-view.coffee#L85-L96

The generated view for an item doesn't need to contain the text you typed, for example, you could use it to show images and use the text you type to filter images somehow. Or it could contain some text that the user of the component doesn't want highlighted in this way. Maybe subclassing SelectListView might be a better fit?

**Comment by mnquintana** [comment]
@izuzak Ah, you're right. Subclassing SelectListView would work better, but I'm not totally sure about the deprecation status of these Views so I'd be hesitant to do it.

**Comment by mnquintana** [comment]
Added in fuzzy-finder v0.84.0 - should be in the next Atom release (0.199.0)!
