### ISSUE TITLE
too much cpu

### ISSUE THREAD

**Issue by andre-dietrich** [atom/fuzzy-finder#112]
Hi, I do not know why, but I had to disable the fuzzy-finder because it required too much CPU (100%) without it, atom works fine...

**Comment by izuzak** [comment]
@andre-dietrich Can you share a bit [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)?

**Comment by sagarpanchal** [comment]
https://github.com/atom/fuzzy-finder/issues/216

**Comment by sagarpanchal** [comment]
@izuzak https://github.com/atom/fuzzy-finder/issues/216

**Comment by sagarpanchal** [comment]
@andre-dietrich @izuzak https://github.com/atom/fuzzy-finder/issues/216

**Comment by pierrre** [comment]
@sagarpanchal please stop this spam.
You can edit your previous Github messages.

**Comment by sagarpanchal** [comment]
@pierrre 
I did't spam, I deleted them.

**Comment by pierrre** [comment]
@sagarpanchal yes, but when you delete and create a new message, it sends a new email/notification.
That's why it's preferable to edit a message.

**Comment by pierrre** [comment]
@sagarpanchal yes, but when you delete and create a new message, it sends a new email/notification.
That's why it's preferable to edit a message.

**Comment by pierrre** [comment]
@sagarpanchal yes, but when you delete and create a new message, it sends a new email/notification.
That's why it's preferable to edit a message.

**Comment by pierrre** [comment]
@sagarpanchal yes, but when you delete and create a new message, it sends a new email/notification.
That's why it's preferable to edit a message.

**Comment by pierrre** [comment]
@sagarpanchal yes, but when you delete and create a new message, it sends a new email/notification.
That's why it's preferable to edit a message.

**Comment by 50Wliu** [comment]
Closing as no new information has been provided.
