### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/robertschaaf/Downloads/Atom.app/C...

### ISSUE THREAD

**Issue by rschaaf** [atom/fuzzy-finder#118]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package, v0.87.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/*****/Downloads/Atom.app/Contents/Resources/app.asar'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/Users/******/Downloads/Atom.app/Contents/Resources/app.asar'
    at Error (native)
    at fs.openSync (fs.js:544:18)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
    at Object.loadFile [as .js] (/Users/*******/Downloads/Atom.app/Contents/Resources/app.asar/src/babel.js:138:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.createProjectView (/User/*****/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:88:23)
    at atom-workspace.atom.commands.add.fuzzy-finder:toggle-file-finder (/Users/*****/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/main.js:24:26)
```

### Commands

```
     -9:55.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:54 core:move-down (atom-text-editor.editor.is-focused)
  5x -9:49 core:backspace (atom-text-editor.editor.is-focused)
     -9:40 core:move-left (atom-text-editor.editor.is-focused)
     -9:33.1.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -9:33.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:26.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by rschaaf** [comment]
This happened when I said "talky" while using atom.

**Comment by izuzak** [comment]
@rschaaf Can you reliably reproduce this? Can you reproduce after you move Atom.app to the Applications folder in OSX?

**Comment by rschaaf** [comment]
I restarted atom, and I'm no longer able to reproduce the error.

**Comment by mnquintana** [comment]
@rschaaf Were you running Atom out of your Downloads/ folder?

**Comment by rschaaf** [comment]
I apologize; I realize now that I failed to answer your question the first time.

Yes, I at one point was running it out of the downloads folder.  When I got the error the first time, I had already moved Atom to the Applications folder, but I don't think I had since restarted it.

**Comment by izuzak** [comment]
> Yes, I at one point was running it out of the downloads folder. When I got the error the first time, I had already moved Atom to the Applications folder, but I don't think I had since restarted it.

I think that explains things -- Atom was still running and tried to load more resources from the previous location, but there was nothing there since you moved it to the new location. If you run into this again -- let us know.
