### ISSUE TITLE
Remove duplication of toggle-file-finder shortcut

### ISSUE THREAD

**Issue by adius** [atom/fuzzy-finder#129]
Why are there 2 shortcuts for toggle-file-finder?
It seems like it would make much more sense to use only `cmd-T` to toggle the file-finder and use `cmd-P` for something else. Maybe even replace `cmd-shift-P` with `cmd-P`, as it is "probably the most important command in Atom" (as stated in the flight manual) and should therefore better be assigned to a  2 key instead of a 3 key shortcut.

**Comment by 50Wliu** [comment]
Please see #78, #92, and #106, which all aim to solve this problem.
