### ISSUE TITLE
search behavior is inconsistent

### ISSUE THREAD

**Issue by blairanderson** [atom/fuzzy-finder#138]
3rd item should be first
![screen shot 2015-09-09 at 3 52 06 pm](https://cloud.githubusercontent.com/assets/955736/9776338/2b4ed0de-570c-11e5-8788-578c2d28c111.png)

2nd item should be first
![screen shot 2015-09-09 at 3 50 58 pm](https://cloud.githubusercontent.com/assets/955736/9776339/2b4f5374-570c-11e5-896b-1d0868215dd8.png)

becomes first after arbitrary letters are added
![screen shot 2015-09-09 at 3 52 38 pm](https://cloud.githubusercontent.com/assets/955736/9776340/2b5200c4-570c-11e5-8861-44ceba05f60b.png)

**Comment by chamini2** [comment]
Completely agree, the fuzzy finding should award more points to letters next to each other, no spread like the match it shows.

**Comment by kayone** [comment]
I'm really surprised this isn't getting any attention, I could type the full name of a file and it shows me items that don't really match what I type. this is a pretty core part of the editor and it's basically broken.

**Comment by 50Wliu** [comment]
> I'm really surprised this isn't getting any attention

It has.  In the latest betas you can now turn on the experimental "Use Alternate Scoring" option.  I'm also going to close this in favor of #57 (and also jeancroy/fuzzaldrin-plus#1).
