### ISSUE TITLE
0.90.0 not available in my Atom

### ISSUE THREAD

**Issue by walles** [atom/fuzzy-finder#143]
Hi!

I'm using Atom 1.0.19 on OS X 10.10.5.

My Atom says that `fuzzy-finder` is at version `0.88.0`.

I would have expected Fuzzy Finder to be at `0.90.0` (which was released almost a week ago now).

If I go to Settings / Updates and Check for Updates, I'm informed that "All of your installed packages are up to date".

Other packages seem to update just fine; I get updates from time to time.

Is this a problem with my Atom installation? Is it something you need to do in your end to have Fuzzy Finder actually go out to users?

How can I debug this?

Regards /Johan

**Comment by mehcode** [comment]
Built-in packages are locked at what Atom's package.json defines.

https://github.com/atom/atom/blob/v1.0.19/package.json#L96

**Comment by thomasjo** [comment]
As pointed out by @mehcode, this package is bundled with Atom and v0.90.0 (or later) will be available in the next release of Atom (most likely v1.0.20).
