### ISSUE TITLE
Option to ignore VCS excluded paths?

### ISSUE THREAD

**Issue by JesseLeite** [atom/fuzzy-finder#148]
I know this sounds a bit crazy, but I have the `Exclude VCS Ignored Paths` option checked so that I can do a project-wide find and replace without touching vendor dependencies.

![screen shot 2015-10-29 at 5 24 29 pm](https://cloud.githubusercontent.com/assets/5187394/10832535/648021fa-7e62-11e5-8a0d-adf17a7265c6.png)

For example, I'm a heavy Laravel user, which uses PHP composer to pull dependencies into my project's /vendor folder.  The exclude VCS option is great for limiting find/replace scope, but I often find myself trying to look up vendor source code using the fuzzy finder, for documentation purposes.  It's often faster for me to fuzzy finder into a vendor class to learn about available methods, than it is for me to open browser and hunt through web-based docs.

![screen shot 2015-10-29 at 5 23 20 pm](https://cloud.githubusercontent.com/assets/5187394/10832661/0e2ad5ec-7e63-11e5-95d4-782569f0cd01.png)

All that said, it'd be nice if we could somehow configure fuzzy-finder to ignore that `Exclude VCS Ignored Paths` option.  Thoughts?

**Comment by thedaniel** [comment]
There's probably some way to provide this functionality within the editor, I know I find myself dropping into the terminal and using grep for it from time to time - I'm not sure if that is a setting, or a separate fuzzy-finder command for searching the full project without ignores. In any case, I'll add some labels and cc @atom/feedback for now.

**Comment by asiniy** [comment]
+1

**Comment by JesseLeite** [comment]
Thanks @thedaniel.  I like the idea of separate fuzzy-finder command for searching full project without ignores.  Not sure how to implement though, because Amateur.

**Comment by kaicataldo** [comment]
I'd love to see this functionality, either by:
 - being able to bind a second keymapping that will search the entire contents of the directory whether the "Exclude VCS Ignored Paths" is set or not
 - starting the search query off with a character that denotes that this should search the entire directory

My preference is for the former. I'd be happy to try to implement this if it's something that would be accepted :smile:

**Comment by tiagocpontesp** [comment]
+1

**Comment by davesnx** [comment]
Thanks @50Wliu, and sorry :(

**Comment by jacquescrocker** [comment]
+1, this would be insanely useful

**Comment by tienduccao** [comment]
+1, this is the exact feature I'm looking for

**Comment by caillou** [comment]
I regularly miss having a shortcut to tell fuzzy-finder to search in the ignored files. The most common reason is that I would like to look at the implementation of a file in the `node_modules` folder.

Ideally this would be implemented as a keybinding or leading character (like `:` for `jump to line`).

Is there a major difficulty in implementing such an option?

**Comment by nathansobo** [comment]
No major difficulty other than ironing out the UX and taking time away from other things. Want to give it a shot?

**Comment by caillou** [comment]
@nathansobo Not having worked on any atom related code before, I might first choose to work on [Beginner issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Abeginner+label%3Ahelp-wanted+user%3Aatom+sort%3Acomments-desc).

Or would you consider this one a fairly simple task? If so, could you give me a hint or two as to how you would get started on this? I have worked with CoffeeScript for over a year, so this should not be a problem.

**Comment by bboure** [comment]
I vote for this one too. I often find myself want to lookup vendors for the same reasons as explained above. Would be great to be able to exceptionally bypass the ignored paths with a specific command.

Might also be useful to "remove" a file/directory from the ignored paths (i.e.: add it back to the index)
e.g.: You have a non-versioned secret file or custom config file and still want to search for it.

**Comment by stevgouws** [comment]
+1

**Comment by smonetti** [comment]
+1

**Comment by jacktuck** [comment]
+1

**Comment by lee-dohm** [comment]
Thanks everyone for the feedback on this idea :+1:

This is something that we agree that would be beneficial. It isn't something that the Atom maintainers team is going to be addressing ourselves in the near future though. Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that we aren't going to be working on ourselves to be more transparent about what it is we are planning on working on and what we aren't.

We would be interested in evaluating a well-written pull request for this though, so I'll leave the `help-wanted` label on this so others can find it more easily.

Thanks again for your interest in Atom!
