### ISSUE TITLE
Freezes in big projects since v 1.2

### ISSUE THREAD

**Issue by voylinux** [atom/fuzzy-finder#155]
The fuzzy finder freezes in projects with a huge number of files. I can see the counter of indexing files but it stops progress when it arrives to about 739,000 .

Every time I close the editor it begins indexing again, so I can never get to use the fuzzy finder.

It was not happening in previous versions of the editor.

**Comment by lee-dohm** [comment]
Do you have a public repository where you can reproduce this issue? (Sorry, I just don't have one this big to try it on :laughing:)

**Comment by voylinux** [comment]
No, sorry. It is a private project. :(
I think this may be because it is also reading dependencies folders or folder already in the gitignore file.

**Comment by voylinux** [comment]
Ok, I think I found the problem.
The package was trying to index some folders wich are symbolic links to other folders, so looks like becomes crazy.

Is there a way to just ignore symlinks instead of specify folders names in ignore option?

**Comment by lee-dohm** [comment]
It sounds like this might be a duplicate of #134?

**Comment by voylinux** [comment]
Yes, I think so.
