### ISSUE TITLE
Use a more realist debounce time

### ISSUE THREAD

**Issue by jeancroy** [atom/fuzzy-finder#156]
This issue exist to helps issue such as  https://github.com/atom/fuzzy-finder/issues/153, as well as general responsiveness on slower computer or larger project. 

Currently fuzzy-finder inherit it's debounce delay from space-pen/select-list-view at [50ms](https://github.com/atom/atom-space-pen-views/blob/master/src/select-list-view.coffee#L21)

I understand we want instant result. A good definition of instant could be "as fast as one can type"
How fast do we type ? A quick google search tells me:

> The average person types between 38 and 40 words per minute -- between 190 and 200 characters per minute. (avg 5 char per word)

That is 3 characters per second.

> An average professional typist types usually in speeds of 50 to 80 wpm -- about 250-400 characters per minute. 

That is 4 - 6 characters per second.

---

50 ms delay = 20 characters per second **!**
150 ms delay = 6.66 characters per second
200 ms delay = 5 characters per second 
300 ms delay = 3.33 characters per second.

---

Fuzzaldrin have a 60k files benchmark.
It takes 150ms to run on a current year computer and about double on a 4 year computer.

Starting atom in my home folder, I have about 70k files.

---

The thing about the current delay is that it is VERY SHORT. 
Literally, it's very hard to trigger, unless we hold a key and let the OS repeat it.

I believe a good rule of thumb for debounce is to not send request faster than we can compute them.

Now, how fast we can compute those results ? The answer to that question really depend on the project and the machine, and because of that, I really prefers to [measure it](https://github.com/atom/autocomplete-plus/issues/541) rather than use a magic number.

With that being said, if a magic number it must be, a lot of things seems to point to just under 300ms.

**Comment by lee-dohm** [comment]
> I understand we want instant result. A good definition of instant could be "as fast as one can type"

The industry accepted definition of "instant" [based on usability research](http://www.nngroup.com/articles/response-times-3-important-limits/) is 100ms.

Those figures on the average layman and average professional typist are sustained, long-form typing. When someone types in short bursts, especially from muscle memory ... they're going to be typing a lot faster.

**Comment by jeancroy** [comment]
Fair point.

With that being said, the current behavior when user type faster than computation time is that the keyboard event get registered to a queue and played back later.

So a lag is going to be there anyways. The difference is one case have a 100% cpu lag, and discard computation as soon as it get done, and the other case wait idle or do other gui stuff while waiting.

Even 100ms that would be twice the room for computation.

**Comment by lee-dohm** [comment]
I'm not arguing against the debounce time being longer. I'm just trying to point to research on the subject :grinning:

**Comment by jeancroy** [comment]
Alternatively:

Fuzzaldrin have no dependency and only do number crunching. Possibly a good candidate for a webworker. If a query is not finished when we receive new input, it can be cancelled and recomputed.

**Comment by dansgithubuser** [comment]
I'd also appreciate something along these lines! Some thoughts: maybe a debounce time setting, or a setting which allows the user explicitly perform a search.

**Comment by dansgithubuser** [comment]
I'm working on configurable debounce time... https://github.com/dansgithubuser/fuzzy-finder/commit/3aa932ca8f525904ea045de334779973c82ed400
Not sure how to make a spec for this. Number of items in list stays at 0.

**Comment by 50Wliu** [comment]
atom-select-list to the bests of my knowledge does not throttle anything.

**Comment by jeancroy** [comment]
@50Wliu 
The original problem was possibly to little of a debounce time. IE can lead to lag on large file list.
No debounce = debounce of 0 = still possibly a too low of a debounce time.

I'll admit that I haven't re checked the performance of it tho.

**Comment by 50Wliu** [comment]
Ah, I misread.  Unless it seems like the lack of debouncing is causing a performance issue though, I think I'm going to keep this closed.
