### ISSUE TITLE
Fuzzy find and show results from selection?

### ISSUE THREAD

**Issue by wonderbeyond** [atom/fuzzy-finder#161]
![image](https://cloud.githubusercontent.com/assets/228361/11704975/4bda2606-9f27-11e5-8e4c-7de0487787f7.png)
Is there an easy way to fuzzy find files from the selection?

**Comment by lee-dohm** [comment]
Not currently, no. Though this sequence doesn't seem terribly complicated:

1. Copy keybinding
1. Fuzzy finder keybinding
1. Paste keybinding
1. <kbd>Enter</kbd>

**Comment by stowball** [comment]
I'm so used to this feature from Brackets. It's a shame Fuzzy Finder doesn't support it as it reduces 2 keystrokes. Efficiency++ :D

**Comment by danielsiwiec** [comment]
I'd love to see this too

**Comment by JosephDAM** [comment]
Hi @lee-dohm , first of all ty for the fuzzy-finder. For my question, I just wanted to know if this is in development, is already implemented, or if it is goin to be at some point.

Regards

**Comment by 50Wliu** [comment]
@JosephDAM This feature is currently not in development, though we would accept a well-crafted PR adding this functionality.

**Comment by ColCh** [comment]
Just to notify subscribed people, I've created PR for this feature: https://github.com/atom/fuzzy-finder/pull/314

It works for all type of fuzzy-finders - `Find File`, `Find Buffer`, `Find Modified File`

**Comment by stowball** [comment]
Can't wait to try it out, https://github.com/ColCh. Thanks a lot!
