### ISSUE TITLE
Fuzzy Finder perpetually "reindexing project"

### ISSUE THREAD

**Issue by sirianni** [atom/fuzzy-finder#162]
In one of my atom workspaces, the Fuzzy Finder always shows "reindexing project".  This seems to have occurred after a recent atom upgrade.  This project does not have an exorbitant number of files (<1000).

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/fuzzy-finder/issues/88. Please subscribe to that issue for updates.
