### ISSUE TITLE
Text is not selected on toggling finder

### ISSUE THREAD

**Issue by pvorona** [atom/fuzzy-finder#169]
1. Open finder
2. Type something and close it (esc by default)
3. Open finder again. Previously typed text still there and its very nice. Finder acts like this text is selected wich is also amazing. But the text itself is displayed without selection background wich is wrong. I'm using One-Dark theme

**Comment by 50Wliu** [comment]
No repro with `Preserve Last Search` checked, closing.  If you're still able to reproduce this please give more detailed reproduction steps.
