### ISSUE TITLE
Fuzzy Finder only re-indexes when window focus changes

### ISSUE THREAD

**Issue by sirianni** [atom/fuzzy-finder#170]
Looking through the code in `project-view.coffee`, this seems to be by design.  I guess the assumption is that every action that can add/remove a file requires a separate dialog box (confirm delete, new file).

However, new files can be added via Tree View (Tree View : Add File) without changing focus to a separate window.  Therefore, such files are not reflected in the Fuzzy Finder until the window focus is manually toggled.

Is there a event emitted by Tree View that could be listened to?

**Comment by jimbonator** [comment]
I'd be happy with a re-index hotkey.

**Comment by 50Wliu** [comment]
Similar enough to #30 that I'm going to close this issue in favor of that one.
