### ISSUE TITLE
Keymaps do not register for linux -- Needs 'atom-workspace'

### ISSUE THREAD

**Issue by dsifford** [atom/fuzzy-finder#171]
Hello,

I figured this issue would be too small to warrant a pull request. 

The default keybindings (at least for linux) requires `atom-workspace` in the selector string in order to function properly.

In other words...

**This..**
```cson
'.platform-linux':
  'ctrl-t': 'fuzzy-finder:toggle-file-finder'
  'ctrl-p': 'fuzzy-finder:toggle-file-finder'
  'ctrl-b': 'fuzzy-finder:toggle-buffer-finder'
  'ctrl-B': 'fuzzy-finder:toggle-git-status-finder'
```

**Should be this...**
```cson
'.platform-linux atom-workspace':
  'ctrl-t': 'fuzzy-finder:toggle-file-finder'
  'ctrl-p': 'fuzzy-finder:toggle-file-finder'
  'ctrl-b': 'fuzzy-finder:toggle-buffer-finder'
  'ctrl-B': 'fuzzy-finder:toggle-git-status-finder'
```

**Comment by aeosynth** [comment]
defaults works fine for me on arch linux

**Comment by 50Wliu** [comment]
@dsifford Can you still reproduce this on Atom 1.7.4 in safe mode (`atom --safe`)?

**Comment by dsifford** [comment]
Can't reproduce this anymore. Must have been fixed in some previous version (or, more realistically, some weird glitch when I first posted this issue).
