### ISSUE TITLE
When opening a file it should be set in pending state

### ISSUE THREAD

**Issue by hultberg** [atom/fuzzy-finder#173]
Currently in the beta of 1.6.0, there is a new feature where single-clicked files from the tree-view is opend as "pending" (italic font style on the tab). I noticed that when searching for a file in the fuzzy-finder it still opens a file as always (normal mode). I would like it to change to pending as it's more sensible. When someone saves the file it will be set as normal anyways.

Using atom 1.6.0-beta3 on ubuntu 14.04
(Feature request)

**Comment by lee-dohm** [comment]
The vision that we have for fuzzy-finder with regard to pending files is that as one navigates through the list, such as via the arrow keys, the currently selected file is shown in a pending state. But when you confirm a specific file is the one you wish to open, such as via <kbd>Enter</kbd>, it will be confirmed, i.e. no longer pending.

We don't have an ETA for when the above behavior will be implemented. You can subscribe to https://github.com/atom/fuzzy-finder/issues/5 for updates.
