### ISSUE TITLE
[mac][php] Fuzzy function list shows vars

### ISSUE THREAD

**Issue by Sylvm** [atom/fuzzy-finder#184]
When using this kind of code :
`<?php

function aaa(){
   $inA = '';
   return false;
}

function bbb(){
   $inB = array();
   foreach(array(1,2,3,4,5) as $val){
      $inB[$val] = 0;
   }
   return false;
}

function ccc($fail = array()){
	$inC = '';
   return false;
}

function ddd(){
   $inD = '';
   return false;
}
`

And using cmd + R to show all function I got :
- aaa
- inA
- bbb
- inB
- ccc
- inC
- ddd
- inD

I expected to see only aaa, bbb, ccc and ddd.

**Comment by mehcode** [comment]
Try looking at https://github.com/mehcode/atom-symbols-plus

It's still a work in progress but simple `cmd+r` is already far more accurate than built-in.

**Comment by Sylvm** [comment]
Thank you very much for the link. 
I installed symbols-plus from @mehcode and it looks fine, I'll report there now for this feature.
