### ISSUE TITLE
Panel takes 2-3 seconds to open

### ISSUE THREAD

**Issue by brendanblackwood** [atom/fuzzy-finder#188]
When I hit <kbd>Cmd</kbd>+<kbd>t</kbd> to open the fuzzy finder, it takes 2-3 seconds for the panel to open. This doesn't seem to be related to reindexing (that I can tell) because if I've just opened atom, it will start reindexing and show me that when I first open it. 

I've tested this using v1.7.0-beta3 (though this has been happening since v1.7.0-beta0) in safe mode and see the problem there as well so it doesn't seem to be a 3rd party package. When testing with v1.6.1, the panel opens near instantly.

It seems to be dependent on the size of the project (large rails project takes 2-3 seconds, project with 6 files is near instant).

Fuzzy Finder seemed like the right place for this, but if not let me know.

**Comment by 50Wliu** [comment]
@brendanblackwood out of curiosity...do you still experience slowdowns if the project is not a Git repo?

**Comment by ruimarinho** [comment]
I am also experiencing this delay with v1.7.0-beta3 (and since v1.7.0-beta0).

**Comment by brendanblackwood** [comment]
Same thing with the same project (removed .git*).

**Comment by fixe** [comment]
Temporary fix for the projects I'm working on:

```
"fuzzy-finder":
    ignoredNames: [
      ".git"
      "node_modules/**/node_modules"
    ]
```
```

**Comment by opensourceportfolio** [comment]
I've been seeing the same thing. I thought it was another plugin that I installed so I've been trying to narrow it down. Good thing I'm not the only one.

**Comment by yriveiro** [comment]
I did today the upgrade to last stable version of Atom (1.7). the pane takes an eternity to open indeed compared to 1.6.2 ...

**Comment by danfuzz** [comment]
Also seeing this problem since updating to 1.7 from 1.6.2. The difference was immediately noticeable.

**Comment by M-Porter** [comment]
Did a quick git bisect and ended up with this:
```
7346c18c3b9d73f09d0d000aa3617839d7c7263a is the first bad commit
commit 7346c18c3b9d73f09d0d000aa3617839d7c7263a
Author: joshaber <joshaber@gmail.com>
Date:   Tue Dec 29 16:35:11 2015 -0500

    Get the status from async git.

:040000 040000 33a0f70efa3d7a59719724fdd68dc331530f3c34 9b5eaab665a43e88eb5d1121ae65f8cd75b4a1a7 M	lib
```

Part of https://github.com/atom/fuzzy-finder/pull/167 which makes sense. If you run a profile on fuzzy-finder, `dataForFilePaths` is the slowest function which is what was modified in that commit.

**Comment by M-Porter** [comment]
Reverting commit 7346c18c3b9d73f09d0d000aa3617839d7c7263a instantly made this much much faster. As a quick fix, it should be reverted until a more suitable way of using async git is found to work with atom 1.7+

**Comment by M-Porter** [comment]
https://github.com/atom/fuzzy-finder/pull/192

**Comment by joshaber** [comment]
I can't reproduce this with `atom/atom` open. Can anyone provide some reproduction steps?

**Comment by AEgan** [comment]
How large is the project you're testing it with? For the majority of projects it hasn't been an issue for me, but I've experienced this (about 5-6 second delay for me) in a very large project. ~9k files with  ~25k commits.

**Comment by joshaber** [comment]
I tried it with `atom/atom`.

**Comment by yriveiro** [comment]
With tiny projects the fuzzy finder opens with no delay, if the project has a considerable size, the lag opening the fuzzy finder is in the order of seconds

**Comment by M-Porter** [comment]
`atom/atom` is hardly a large project. its not very deep and it doesn't have symlinks (as far as i can tell) -- symlinks shouldn't be an issue but who knows... computers.

The projects I was testing with is:
~30k indexible files (files which aren't ignored from search)
76k+ commits (which isn't a problem because `.git` is ignored from search)

**Comment by joshaber** [comment]
>symlinks shouldn't be an issue but who knows... computers.

Indeed 😆

Sounds like I need to find a bigger project to test again. Lemme know if anyone knows of one.

**Comment by M-Porter** [comment]
A huge project that comes to mind right away would be the [linux kernel](https://github.com/torvalds/linux) at 1+Gb... but thats probably too large. I'll keep thinking.

**Comment by umpirsky** [comment]
I can confirm this. After upgrade to 1.7 `Ctrl + P` got way slower on large project. It now takes 2-3 seconds (just to open dialog) on large project where with 1.6 was instant.

**Comment by m-jch** [comment]
I'm fine, until i was upgraded atom from 1.6 to 1.7, It's very slow now, even i thought migrate to sublime text :(

**Comment by paulatbipsync** [comment]
I can confirm this issue, and have downgraded to 1.6.2 to workaround it for the time being

**Comment by M-Porter** [comment]
Reverting the merge fixes the problem. Can we just do that for the time being until the bug is looked into and resolved?

@joshaber

**Comment by joshaber** [comment]
I'm currently looking into it.

**Comment by BinaryMuse** [comment]
This is fixed in 1.7.2

**Comment by umpirsky** [comment]
Works like a charm, thanks @joshaber, great job! :+1:

**Comment by joshaber** [comment]
Great, thanks for the reports and patience everyone!

**Comment by brendanblackwood** [comment]
Yeah, thanks for the fix. Buttery smooth :)

**Comment by umpirsky** [comment]
Same happens after upgrade from 1.15 to 1.16. Should we reopen?

**Comment by dwelle** [comment]
There's also a new issue of the text typed into the panel being entered into the file buffer when the fuzzy-finder lags.

Will create separate issue when I have time.

**Comment by umpirsky** [comment]
Yes, that as well, since it's very slow, it happens almost each time after upgrade. Please link this new issues here, it'd be useful to track them. Thanks.

**Comment by dwelle** [comment]
@umpirsky just came across https://github.com/atom/fuzzy-finder/issues/88 which suggests that the reindexing-everytime issue is old and still not solved. How's this a regression since 1.16, then? Or is the regression just related to perf of the reindexing?

I'm obviously seeing what you're seeing, just not sure what exactly changed from 1.15 → 1.16.

**Comment by umpirsky** [comment]
@dwelle Thanks for sharing. For me it's a regression, I'll most likely go back to 1.14.

- 1.15 is broken because of https://github.com/atom/atom/issues/13978
- 1.16 fuzzy finder is slow because of this.
