### ISSUE TITLE
Use es6 instead of coffeescript?

### ISSUE THREAD

**Issue by tnrich** [atom/fuzzy-finder#209]
Hey there,

I am a big fan of atom in general, and have been currently hacking away on the fuzzy finder trying to implement an import system akin to what https://github.com/atom/fuzzy-finder/issues/186 suggests. The one thing is ...it's written in coffeescript which makes everything a lot more difficult for me (and I imagine most other naive atom users).

I know there have been many discussions about this, but, I thought I'd ask in a place which might actually change (as opposed to debating whether or not the whole core of atom should be converted)... is there any chance this package could be converted to vanilla ES6 js?

Sorry to bring this up if it is a sore subject. 

Cheers,
Thomas

**Comment by Alhadis** [comment]
As an ES6 lover who has difficulty "adjusting" to CoffeeScript, I'm inclined to agree with you.

However, I can't see the Atom team moving away from the language the project's been founded on. There'd be nothing to gain from doing so: everybody's workflow would be disrupted.

**Comment by lee-dohm** [comment]
We're not planning on converting anything at this point in time. When it makes sense, new files will be written in ES6. At some point, we might convert. Currently, [there are performance gotchas with ES6](https://groups.google.com/forum/m/#!msg/strengthen-js/ojj3TDxbHpQ/5ENNAiUzEgAJ) that make wholesale conversions not attractive at this point:

> idiomatic ES6 code currently is substantially slower than ES5, across all browsers -- easily by 2x, often by 10x or more.

The above holds true with some of our experimental observations as well.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For questions like these, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by tnrich** [comment]
Thanks for the explanation. Sounds good!

**Comment by YurySolovyov** [comment]
With newer node/V8/electron releases, is performance still a concern?

**Comment by lee-dohm** [comment]
No, but we're still not going to convert simply for the sake of converting.

**Comment by YurySolovyov** [comment]
Will you accept a PR tho?

**Comment by lee-dohm** [comment]
I don't know. I'll bring it up to the team. My personal opinion is that a change of that nature would be high risk for very low reward.

**Comment by lee-dohm** [comment]
@YurySolovyov The team discussed it and here's what we came up with:

1. Any conversion PR would have to convert **code only** because if it converted code _and_ tests we would have no sane basis for validation
1. Converting the code is a **big** PR to review, so would naturally tend to gravitate to the bottom of the pile anyway
1. Converting the code essentially invalidates every open PR, so we're more likely to accept conversions on repos where there are few open PRs
1. Keeping such a PR up-to-date with ongoing changes to the code would be tough on the submitter

What this says to us is that _in theory_ we would be willing to review a PR for a code conversion. In practice, because of the above there is little likelihood of such a PR being merged outside of the much less active repos.

**Comment by YurySolovyov** [comment]
How about converting one file per PR?

**Comment by Alhadis** [comment]
@YurySolovyov I think you'll find that over time, each CoffeeScript file gets rewritten as JavaScript whenever there's a need to add new code. The `tree-view` package has [already started](https://github.com/atom/tree-view/tree/master/lib) this transition, as you can see. =)

Personally, I feel this is the safest, most "natural" way to phase out CoffeeScript. Like @lee-dohm said, converting it all at once would cause a lot of noise with open PRs (not to mention the mess it'd inflict on customised forks). At the end of the day, you wouldn't have actually solved any existing problems, either.

FWIW, I can't stand CoffeeScript, and I'm actually eager to see all traces of it purged from Atom's codebase. But it doesn't need to be an immediate process.
