### ISSUE TITLE
Cannot ignore directories

### ISSUE THREAD

**Issue by wylieconlon** [atom/fuzzy-finder#22]
Reading through the `load-paths-handler` source, it looks like the `ignoredNames` config only matches the file name without extension (the base name). This obviously doesn't work when you want to specify an ignore on a directory level, such as for build products or dependencies.

I would prefer to specify ignores with a syntax like [`.gitignore`](http://git-scm.com/docs/gitignore), from the root of the current project. For example:

```
'fuzzyFinder':
  'ignoredNames': [
    'public/*'
    'bower_components/*'
    'node_modules/*'
  ]
```

**Comment by vtsirkinidis** [comment]
This guy nails it:
https://virtual-host-discourse.global.ssl.fastly.net/uploads/github_atom/370/82f5e9a38b76322a.jpg

**Comment by JustinAiken** [comment]
That link is gone; how do ignore a directory (that's not gitignored) ?

**Comment by swaathi** [comment]
The link no longer works. How do I ignore a directory?

**Comment by szymonbaranowski** [comment]
Anyone?

**Comment by ndan** [comment]
Go to `Atom -> Config`, It'll open `config.cson`, then add/edit "fuzzy-finder" section like in the example below:
```
"*":
...
  "fuzzy-finder":
    ignoredNames: [
      "folder_or_file"
    ]
...
```
