### ISSUE TITLE
Indexing Project..0

### ISSUE THREAD

**Issue by Postem1** [atom/fuzzy-finder#226]
Whenever I start the Fuzzy Finder, it gives a screen stating:  Indexing project..0.

How do I get it to work properly?

**Comment by Ben3eeE** [comment]
https://github.com/atom/fuzzy-finder/issues/205?

**Comment by sunnyvempati** [comment]
+1

**Comment by 50Wliu** [comment]
Closing as a duplicate of #205 - feel free to subscribe there for updates.
