### ISSUE TITLE
API - Trigger fuzzy-finder from a custom plugin

### ISSUE THREAD

**Issue by mateusvahl** [atom/fuzzy-finder#242]
Hi,
I'm current creating a plugin and I wish trigger atom `fuzzy-finder` with a custom text.
It's current possible to do that ? Can someone give me a example?
I didn't found anything related in atom API about how require core modules.
Let me know if I'm missing something :D

Thanks for the help!

**Comment by dschwen** [comment]
I'd be very interested in that, too. My switch-header-source plugin dschwen/switch-header-source#11 could be more flexible if I could you the already existing index of the fuzzy finder. Rolling my own index seems like unnecessary duplication of work.
