### ISSUE TITLE
Ignored Names not ignoring

### ISSUE THREAD

**Issue by stoplion** [atom/fuzzy-finder#252]
Adding `node_modules/*` still searches node_modules.

**Comment by lee-dohm** [comment]
Can you give us some steps to reproduce the problem? I'm not sure where you're suggesting to add `node_modules/*`.

**Comment by lee-dohm** [comment]
Please let us know if you have any more information you can share. When we get more information, we can reopen the Issue.

**Comment by tjkohli** [comment]
I have ignored a .css file in my folder, and it still shows up. It's grayed out in the sidebar but still shows in the fuzzy search. I'm happy to submit any logs or help as needed.
