### ISSUE TITLE
Alt+Enter to open in second pane (Xcode style)

### ISSUE THREAD

**Issue by kasperpihl** [atom/fuzzy-finder#260]
I'm coming from Xcode, and I really love how powerful it is to work with split panes there.

A setting to open the file in the second pane on alt-enter and the first pane on enter would be really nice.

Is this meant to go here or can I extend this somehow with a package?

Thanks

**Comment by lee-dohm** [comment]
The fuzzy-finder already has the ability to do this. You can use the following keybinding in your `keymap.cson` to get what you want:

```
'.fuzzy-finder':
  'alt-enter': 'pane:split-right'
```
