### ISSUE TITLE
Please make fuzzy finder open with selected text prefilled

### ISSUE THREAD

**Issue by nshikov** [atom/fuzzy-finder#279]
E.g. usually files named similar to classes they contain, and I can select for example AppointmentUtil text and click cmd-p and fuzzy finder opens with AppointmentUtil text in search input, so I can just click enter and open file AppointmentUtil.ts . Otherwise have to use cmd-c => cmd-p => cmd-v or type it manually to achieve same.

**Comment by phearlez** [comment]
Seconded on this; I end up doing a cmd-c,cmd-p,cmd-v at least a dozen times a day.

**Comment by brianmcgue** [comment]
Would love to see this.

**Comment by mitch104** [comment]
This issue can now be closed, you can achieve this by checking `Prefill From Selection` in the fuzzy-finder settings :+1:

**Comment by Arcanemagus** [comment]
Closing based on the above comment 😉.

**Comment by ohboyd** [comment]
Yesss, thanks for making this and for explaining it! Finally solved my problem trying to use atom's fuzzy finder with selected text! To save an extra potential google step for the next person:
- Hit `cmd-,`
- Go to your packages
- Search for the fuzzy-finder package
- Check `Prefill From Selection` like @mitch104 mentioned
