### ISSUE TITLE
fuzzy-finder doesn't withhold keyboard events that fire during re-index and panel opening

### ISSUE THREAD

**Issue by dwelle** [atom/fuzzy-finder#288]
### Prerequisites

 * [x] Reproduced the problem in Safe Mode
 * [x] Checked that your issue isn't already filed

### Description

Since `1.16.0` either the project reindexing perf drastically downgraded, or there's a regression (or both) that causes the text typed after user hits `ctrl + p` being added to editor instead of the fuzzy-finder panel, provided user starts to type _before_ reindexing is done and panel opens.

AFAIK this never happened to me before and I always start to type well before the panel opens (waiting for and ensuring the panel is open before typing is really bad UX).

This causes major problems if one's not careful and the nonsense text goes through linting, CRs etc. (not that often -- but still causes major pain due to constant refactor, backtracking etc.)

### Steps to Reproduce

1. open a project with moderate amount of files so that reindexing takes considerable time (0.5-1s+)
2. blur & refocus atom to [ensure reindexing](https://github.com/atom/fuzzy-finder/issues/88)
3. `ctrl + p` and start typing right away

**Expected behavior:** should enqueue the keyboard events until the panel opens (or whatever other implem), and seamlessly paste whatever user typed before it opened

**Actual behavior:**  the text that's typed _before_ the panel opens is entered into file buffer

**Reproduces how often:** 100% (well, practically every time I fuzzy-search for file after de-focusing atom, which is nearly always)

### Versions

atom `1.16.0`, fuzzy-finder `1.5.0`, win 7

### related

- [#188 - Panel takes 2-3 seconds to open](https://github.com/atom/fuzzy-finder/issues/188)
- [#88 - Fuzzy finder reindex whole project everytime](https://github.com/atom/fuzzy-finder/issues/88)

If I checked correctly, between atom `1.15.0` → `1.16.0`, one related bump happened:

- `fuzzy-finder` between `1.4.1` → `1.5.0`

**Comment by 50Wliu** [comment]
Thanks for opening a new bug report @dwelle.  I've edited it slightly because some of your version investigations weren't correct, but many thanks for taking the time to do that research :).

This looks like a regression caused by the removal of jQuery.
/cc @as-cii

**Comment by iolsen** [comment]
@as-cii can you investigate this one? Looks related to jquery removal.
