### ISSUE TITLE
Can't find files that have been .gitignored

### ISSUE THREAD

**Issue by donovanbray** [atom/fuzzy-finder#29]
I have a number of files that have an extension .template that are checked into git. The developer copies the database.yml.template to database.yml in order to run the project.  To prevent the customized templates from being checked in they are added to the .gitignore.

However when you search with fuzzy finder it will refuse to show you the the .gitignored version, only the database.yml.template is shown.

sublime shows both versions with the shorter version being prioritized higher.

**Comment by synth** [comment]
Just getting started with Atom editor. Drove me crazy why fuzzy finder wasn't finding files until I realized the commonality of .gitignored files weren't showing up. _Strange default setting, no?_ Just because its in .gitignore still means I want to be able to find and edit those files.
