### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, lstat 'Z:/opt'

### ISSUE THREAD

**Issue by egno** [atom/fuzzy-finder#290]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.0

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, lstat 'Z:\opt'

```
At fs.js:982

Error: EISDIR: illegal operation on a directory, lstat 'Z:\opt'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Object.realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:19:21
    at Array.map (native)
    at Object.startTask (/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:17:46)
    at Object.startLoadPathsTask (/app.asar/node_modules/fuzzy-finder/lib/main.js:117:39)
    at /app.asar/node_modules/fuzzy-finder/lib/main.js:31:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.6.3 
atom-beautify 0.29.22 
atom-formatter-jsbeautify 1.1.2 
atom-typescript 11.0.2 
auto-encoding 0.7.0 
autoclose-html 0.23.0 
autocomplete-python 1.8.63 
busy-signal 1.3.0 
floobits 0.32.10 
git-plus 7.5.0 
git-time-machine 1.5.9 
haskell-debug 0.2.1 
haskell-ghc-mod 1.19.9 
haskell-grammar 0.4.0 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.2 
ide-haskell-hoogle 0.0.6 
intentions 1.1.2 
language-haskell 1.12.1 
language-pgsql 0.2.3 
language-vue 0.21.2 
linter 2.1.4 
linter-tslint 1.1.0 
linter-ui-default 1.2.3 
minimap 4.27.1 
quick-query 0.9.2 
save-with-encoding 0.1.1 
sync-settings 0.8.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by egno** [comment]
I try to open a remote project folder.
My project: https://github.com/egno/crocogame_bot
It runs on the remote ubuntu server.
I connect the remote disk as Z: in Windows 10 with the 'SFTP Net Drive Free' application.

Yes, the error is reproducible. I see the error in safe mode.

**Comment by rsese** [comment]
Thanks for the details - does the error prevent you from working on any files in that directory?

**Comment by rsese** [comment]
From https://github.com/atom/atom/issues/16695:

> 1. Created empty file tasks.py in Windows 10 (1709).
> 2. Rightclicked on file and open in Atom

**Comment by nogetfx** [comment]
Hi
I can reproduce the error. I created an empty file, renaming it task.py and opened it in Atom. Like @egno the file was located on a SSH share mapped with SFTP Net Drive 2017 (Version 17.0.0.537, Driver 6.1.184.118). 
I get no error when opening an empty file from local directory.

**Comment by rsese** [comment]
From https://github.com/atom/atom/issues/16843:

> Open folder stored on my raspberry pi connected with SFTP Net Drive 2017
