### ISSUE TITLE
Regression in highlight with alternate scoring.

### ISSUE THREAD

**Issue by jeancroy** [atom/fuzzy-finder#296]
Since about atom 1.1, the alternate scoring option is provided that decide both how to rank and highlight the result.

On current version, alternate scoring option only decide ranking, and it seems highlight is always rendered using classic fuzzaldrin.  I think it's important to have both together as I consider  highlight an explanation of current ranking.

It's very probable the behavior broke when switching the underlying component to remove jquery.
It's hard to detect  because there's no test for it and one must be in knowledge of the algorithms to spot the differences.

------------------------------

Here's a recent [example](https://github.com/atom/fuzzy-finder/issues/21#issuecomment-301957502), typical of classic fuzzaldrin.

One can see that the word `member` is split because classic fuzzaldrin select first occurence of `m` then first occurence of `e` following that m then first `m` then `ber`

![img](https://cloud.githubusercontent.com/assets/490562/26134321/e1633240-3b01-11e7-93cf-715e2da67e78.png)

Here's a reference highlight with fuzz-aldrin-plus outside of atom. One can see that the algorithm try to group matches together instead of processing greedy left to right.

![img](https://cloud.githubusercontent.com/assets/12763666/26139983/49208bd6-3aa2-11e7-98f9-d8db304e3134.png)

Now that algorithm isn't perfect and here we have an issue with `-payment` being before plain edit.
But the overall highlight seems more intuitive. 

The reason I write this is that 'scattered letters' was by far the main complains with classic fuzzaldrin and complains stated to reappears.

**Comment by 50Wliu** [comment]
https://github.com/atom/fuzzy-finder/blob/e69a9e23cca40127f93b60e30ab7491df21dd9d3/lib/fuzzy-finder-view.js#L314

**Comment by jeancroy** [comment]
Ok the problem is a bit complicated because there's strong attempt at using proper matcher.
https://github.com/atom/fuzzy-finder/blob/master/lib/fuzzy-finder-view.js#L59-L61

However I can replicate 

**v1.15**
<img width="476" alt="screenshot_1" src="https://cloud.githubusercontent.com/assets/12763666/26285858/007869a8-3e26-11e7-9b34-13ad77f7157b.png">

**v1.17**
<img width="468" alt="screenshot_3" src="https://cloud.githubusercontent.com/assets/12763666/26285875/4b30438a-3e26-11e7-9e26-48e8714e94e2.png">

Both have alternate scoring turned on.
Maybe something broke the propagation of setting in 1.17 ?

**Comment by 50Wliu** [comment]
Looks like a regression with the jQuery removal then.  Thanks for catching this.

/cc @as-cii
