### ISSUE TITLE
Indexing is slow

### ISSUE THREAD

**Issue by mtodd** [atom/fuzzy-finder#3]
Indexing takes almost 10s (it might be closer to 5s, I don't have an exact time) for `github/github`. I know there's a lot of files and `vendor/cache/` is a big source of slowness, but it essentially blocks all finding until it's indexed at least once and after the FS has changed, it has to reindex everything instead of updating the index with the new addition.

Would love to see some speedup here.

**Comment by wi-ski** [comment]
This problem is annoying and killing my UX. Moving to VS code.
