### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Volumes/home'

### ISSUE THREAD

**Issue by MSD200X** [atom/fuzzy-finder#304]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.8

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Volumes/home'

```
At fs.js:982

Error: ENOENT: no such file or directory, lstat '/Volumes/home'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Proxy.realpathSync (fs.js:1657:19)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/path-loader.js:21:27
    at Array.map (native)
    at Object.startTask (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/path-loader.js:19:52)
    at Object.startLoadPathsTask (/Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/main.js:119:45)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/fuzzy-finder/lib/main.js:33:30
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
linter 1.11.21 
linter-eslint 8.0.0 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by Arcanemagus** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment [https://github.com/atom/fuzzy-finder/issues/304#issuecomment-373825744]. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
