### ISSUE TITLE
Uncaught Error: EINVAL: invalid argument, lstat  ~/OneDrive 

### ISSUE THREAD

**Issue by TomForager** [atom/fuzzy-finder#312]
Enter steps to reproduce:  1. ... 2. ... **Atom**: 1.18.0 x64 **Electron**: 1.3.15 **OS**: Microsoft Windows 10 Pro Insider Preview **Thrown From**:  fuzzy-finder  https://github.com/atom/fuzzy-finder  package 1.5.8 ### Stack Trace Uncaught Error: EINVAL: invalid argument, lstat  C: Users ysmff OneDrive      At fs.js:982 Error: EINVAL: invalid argument, lstat  C: Users ysmff OneDrive   at Error  native   at fs.lstatSync  fs.js:982:18   at Object.fs.lstatSync  ELECTRON_ASAR.js:239:16   at Proxy.realpathSync  fs.js:1657:19   at Proxy.fs.realpathSync  ELECTRON_ASAR.js:316:29   at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:21:27  at Array.map  native   at Object.startTask  ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:19:52   at Object.startLoadPathsTask  ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/main.js:119:45   at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/main.js:33:30  at _combinedTickCallback  internal/process/next_tick.js:67:7   at process._tickCallback  internal/process/next_tick.js:98:9      ### Commands         ### Non-Core Packages     atom-beautify 0.30.4  Hydrogen 1.19.0  minimap-plus 4.29.2  pristine-ui 1.1.6  scroll-through-time 0.2.0

**Comment by elubdynasty** [comment]
Looks like I got the same issue here. I re-installed the atom and poof, there's the fuzzy-finder package (logic/unhandled exception issue)

**Comment by 50Wliu** [comment]
Closing in favor of #324 which is better formatted.
