### ISSUE TITLE
Choose already opened file even from another pane

### ISSUE THREAD

**Issue by probablycorey** [atom/fuzzy-finder#34]
(This could be a fuzzy-finder option. Original issue is https://github.com/atom/atom/issues/1303)

## Behavior expected

Opening a file from cmd-b or cmd-p should go directly to the file if it's already opened, regardless of pane.

## Behavior observed

The file is selected if you're in the same pane, but opened new if not.

## Thoughts

This could be behavior that can be had both ways. For example, if you open a file with enter it will go to the already opened file but if you open with shift-enter it opens a new copy in the current pane.

/via @caseycrites

**Comment by jensljungblad** [comment]
:+1: Anything stopping the PR from being merged?

**Comment by nathansobo** [comment]
It's not clear that it's the right default behavior. Would need to be an option.

**Comment by tmunro** [comment]
I've set it as an option in that PR, and it defaults to false.

**Comment by jensljungblad** [comment]
To me cmd+b is about locating a file I have opened, so having it switch to the pane seems like a sensible default. But yes I agree it's not totally obvious. As long as there's an option I'm happy. 



—
Jens Ljungblad

**Comment by despairblue** [comment]
:+1: for merging
