### ISSUE TITLE
Fuzzy find missing a lot of files

### ISSUE THREAD

**Issue by Magnusvb** [atom/fuzzy-finder#36]
Hi
I have a Magento project ( a lot of files and folder levels). But when I try to do a fuzzy find, it looks like not all of the folders/files is searched/find.

The project is mainly .phtml files. And I can look at a file in the file tree, do a fuzzy find on the name - but Atom can not find it. I belive that it have worked before - but not now on version 0.94.

Regards, Magnus

**Comment by kevinsawicki** [comment]
Closing this out in favor of https://github.com/atom/fuzzaldrin/issues/23 which talks about improving the scoring algorithm across all fuzzy find boxes in Atom.
