### ISSUE TITLE
gitignored files aren't being ignore in the fuzzy finder

### ISSUE THREAD

**Issue by trusktr** [atom/fuzzy-finder#362]
I've got some files ignored in `.gitignore` but they aren't ignored by fuzzy-finder.

Are they supposed to be?

**Comment by trusktr** [comment]
My system info:

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.33.0",
  "platform": "darwin",
  "release": "18.2.0",
  "vmpVersion": "1.35.0",
  "vmpConfig": {},
  "activeCommunityPackages": [
    "atom-material-syntax: 1.0.8",
    "aligner-javascript: 1.3.0",
    "atom-vim-like-tab: 1.5.2",
    "autocomplete-modules: 2.2.2",
    "autocomplete-paths: 2.12.2",
    "better-git-blame: 0.4.7",
    "busy-signal: 1.4.3",
    "cursor-history: 0.13.1",
    "docblockr: 0.13.7",
    "ex-mode-sort: 1.0.0",
    "file-icons: 2.1.21",
    "file-watcher: 1.2.6",
    "git-plus: 8.1.0",
    "hey-pane: 1.1.0",
    "highlight-line: 0.12.0",
    "highlight-selected: 0.13.1",
    "hyperclick: 0.1.5",
    "imdone-atom: 2.4.29",
    "indent-guide-improved: 1.4.13",
    "intentions: 1.1.5",
    "keystroke: 0.4.0",
    "linter: 2.2.0",
    "linter-eslint: 8.4.1",
    "linter-ui-default: 1.7.1",
    "linter-ui-plus: 0.3.2",
    "local-history: 4.3.1",
    "minimap: 4.29.8",
    "minimap-bookmarks: 0.4.2",
    "minimap-git-diff: 4.3.1",
    "minimap-highlight-selected: 4.6.1",
    "minimap-linter: 2.2.1",
    "minimap-pigments: 0.2.2",
    "minimap-quick-highlight: 1.0.1",
    "persistent-undo: 1.3.0",
    "pigments: 0.40.2",
    "prettier-atom: 0.55.2",
    "project-plus: 1.0.0",
    "quick-highlight: 0.13.0",
    "split-diff: 1.4.0",
    "teletype: 0.13.2",
    "termination: 0.6.3",
    "todo-show: 2.3.0",
    "trailing-spaces: 0.4.0",
    "tree-view-git-status: 1.5.0",
    "undo-tree: 1.0.0",
    "vim-mode-plus: 1.35.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "zentabs: 0.8.9",
    "editorconfig: 2.2.2",
    "language-jenkinsfile: 0.1.1",
    "language-pug: 0.0.22",
    "language-vue: 0.23.1",
    "language-javascript-jsx: 0.3.7",
    "ex-mode: 0.18.0"
  ]
}
```

</details>

**Comment by trusktr** [comment]
Looks like it ignores `.gitignored` files most of the time. But in this one project I get ignored files. The `.gitignore` looks like follows:

```conf
# common dev and OS files
.DS_Store
node_modules/
dist/
npm-debug.log
yarn-error.log

# Editor directories and files
.idea
*.suo
*.ntvs*
*.njsproj
*.sln

### ignore everything
/*

### except for the following:

# folders
!/src
!/tests
!/examples

# global build, to be published
!/global.js
!/global.js.map

# config files
!/.builderrc
!/.editorconfig
!/.npmrc
!/.gitignore
!/.npmignore
!/package.json
!/*.config.js

# all good projects have a README!
!/README.md
```

**Comment by trusktr** [comment]
I guess gitignore is working properly, because the Atom file explorer shows items grayed out as expected, just that fuzzy-finder apparently isn't following exactly the same rules.

In the following shot, I am able to fuzzy-find files in the grayed-out folders which are gitignored:

<img width="303" alt="screen shot 2018-12-08 at 11 14 09 am" src="https://user-images.githubusercontent.com/297678/49689742-65a61d80-fada-11e8-82b9-0e12ba4625fc.png">

**Comment by rsese** [comment]
Thanks @trusktr - can you update your issue to add the issue template details?

> I guess gitignore is working properly, because the Atom file explorer shows items grayed out as expected, just that fuzzy-finder apparently isn't following exactly the same rules.

Tree view uses its own setting `Settings > Packages > Tree View > Hide VCS Ignored Files` (this setting is toggled by pressing <kbd>i</kbd> when the tree view is focused).  Fuzzy finder uses the `Settings > Core > Exclude VCS Ignored Paths` setting (see the description for that setting).  What do you have for these settings?
