### ISSUE TITLE
Add an option for opened file position inside tab group

### ISSUE THREAD

**Issue by Frk7** [atom/fuzzy-finder#365]
When I open a file with enter key the file opens next to the last focused one.
It would be nice to have a way to open the new file to the last position in the tab group.

**Comment by rsese** [comment]
Thanks for the suggestion!  This is controlled by the atom/tabs package, you can do this now by enabling `Settings > Packages > Tabs > Add New Tabs At End`.

If I'm misunderstanding, please let me know.

Also, for future issues please use the issue template as much as possible, even for feature requests (you can just say "NA" is something isn't applicable) - the template format and details are super helpful for us when triaging issues.

**Comment by Frk7** [comment]
I don't want to change the stardard Tabs behaviour (new tabs after the active one).
Instead in most cases using the fuzzy finder i'm searching and opening a file that isn't related closely to the active one, so I would prefer it to open to the last position of the tab group (using some key combination or another way).

**Comment by rsese** [comment]
Ohh ok, so you really want a keybinding to open a fuzzy finder item as the last tab like it currently works where you can open a fuzzy finder item in a split pane.  Though it's not something the team would prioritize now, I'll mention this suggestion with the other maintainers for you.
