### ISSUE TITLE
Show prompt to enable "fast mode" on large projects

### ISSUE THREAD

**Issue by rafeca** [atom/fuzzy-finder#376]
### Context

Atom 1.37 will ship with two important performance improvements ([[1]](https://github.com/atom/fuzzy-finder/pull/374) and [[2]](https://github.com/atom/fuzzy-finder/pull/369)) on the fuzzy finder, both of them behind config flags and disabled by default (we want to minimize risks of breaking users' workflows by having both of them disabled for a version).

Under the hypothesis that not many people will enable these features if we don't do anything,
we want to show a prompt to a subset of users so they can easily enable them and we can get some early data and potential issues before we enable the feature by default.

### Constrains

These are the constrains that our solution will have:

* It should be shown to users that will benefit the most. from these features. So the benefits received will overweight the potential issues.
* It should have the less amount of friction possible. A user should do the minimum amount of work possible to enable these features.
* We should not spam users. If a user chooses to not opt in, we shouldn't ask him again.
* It should be clear how to disable the features. If something goes wrong, users should know how to go back to the normal fuzzy finder.

### Potential solution

Show a [`Notification`](https://atom.io/docs/api/v1.35.1/Notification) to the user if the crawling process took more than e.g 5s and if the notification hadn't been shown before.

The notification should have clear call to action buttons that don't require the user to navigate to other parts of the application. Example of notification:

<img width="475" alt="Screen Shot 2019-04-01 at 12 35 25" src="https://user-images.githubusercontent.com/408035/55321746-b15e4780-547a-11e9-904f-884e082954fa.png">

### Metrics

In order to understand how successful is this notification, we can log the following data:

* Number of times that the notification was shown.
* Number of times that people enabled fast mode.
* Number of times that people discarded the notification.

**Comment by rafeca** [comment]
I have been pairing with @jasonrudolph early today on this issue and we've pivoted quite a bit from the original idea and improved the whole solution for the prompt.

This is what the new prompt is going to look like:

<img width="597" alt="Screen Shot 2019-04-03 at 19 54 49" src="https://user-images.githubusercontent.com/408035/55501321-76127300-564a-11e9-9c7c-12584c5b04e0.png">

* To make it easier for users to disable the fast mode or report issues (this was something hard to do with the previous solution), we're going to move the prompt directly to the fuzzy finder. There, we're going to show a message that informs the user about the "fast mode".
* Once the fast mode is enabled, the prompt will change to allow users to either disable it or report issues.
* We want that message to be very noticeable by the users but at the same time we want to avoid annoying users every time that they open the fuzzy finder. To solve this, we're going to show the "NEW" label just for a few days (or X times that the fuzzy finder gets opened) and then only show the message afterwards. We may want to show a "Do not ask again" option.
* When the user clicks the prompt, a notification similar to the original one will be shown. The notification message will be different based on whether the user is enabling the fast mode or it's disabling it.
* We're going to keep the logic to show the prompt only on large projects.

I'm gonna send a WIP PR with the initial work that we and @jasonrudolph have started.

**Comment by jasonrudolph** [comment]
Now that https://github.com/atom/fuzzy-finder/pull/378 is merged, I think we can close this issue.

@rafeca: If this issue should remain, open please feel free to re-open it.
