### ISSUE TITLE
use fuzzy find to open folder

### ISSUE THREAD

**Issue by benzen** [atom/fuzzy-finder#49]
When using fuzzy finder, i'd like to also open folder.
Maybe presenting it with different icon, just to assure that it's a folder, not a file

**Comment by dwelle** [comment]
I think it'd still be very cool if the fuzzy finder displayed folders, too, and focus in tree-view as OP suggests. Or at least if query ends in `/`.

Use case: you know the name of target folder but can't quickly recall any file that's in it.

**Comment by yubaoquan** [comment]
I also want to focus a folder by searching it in fuzzy-finder. When there are a lot of folders, sometimes I do not only need find file but also folder.
