### ISSUE TITLE
Better way to open a new file in a new pane

### ISSUE THREAD

**Issue by dmnd** [atom/fuzzy-finder#58]
Please let me know if there's a better way, but as I understand right now this is how to open a new file in a new pane:

1. `cmd-b right` Split the current pane in the desired direction
2. `cmd-k cmd-w` Close the split file that you don't really want anyway
3. `cmd-T` To find the new file
4. `enter` to open in current (new) pane

Things get a bit more confusing if you have Atom set to destroy empty panes.

Anyway, I was wondering if there is a better way to do this. Is there (A) a way to create an empty pane so steps 1 & 2 could be combined? Alternatively, would it make sense to have something (B) like the following:

1. `cmd-T` To find the file, but don't press enter!
2. `cmd-k right` to open the selected file in a new pane

I think A is probably the better option, but maybe both A and B should exist?

**Comment by lee-dohm** [comment]
Sounds like this has regressed, see:

https://discuss.atom.io/t/any-way-to-open-items-in-the-file-finder-to-a-new-pane/27553

@amytruong Can you reproduce this for me?

**Comment by amytruong** [comment]
@lee-dohm sorry for the delay but yes, was able to reproduce on stable. :cry:
Steps 3, 5, and 6 are the regression:

1. command+T
2. type file name
3. open file with ENTER 
4. command+K+RIGHT
5. click file opened in left pane
6. command+W to close file in left pane

**Comment by kuychaco** [comment]
I believe this was fixed in https://github.com/atom/fuzzy-finder/pull/189
/cc @lee-dohm @amytruong

**Comment by lee-dohm** [comment]
Confirmed that this is fixed in the latest `master`.
