### ISSUE TITLE
Filenames with UTF-8 characters are not found

### ISSUE THREAD

**Issue by gjtorikian** [atom/fuzzy-finder#69]
![utf8](https://cloud.githubusercontent.com/assets/64050/5949816/d404b77c-a706-11e4-8c8e-410f989c7262.gif)

**Comment by gjtorikian** [comment]
The search string was `erstiebegrüßung`.

**Comment by kevinsawicki** [comment]
Looked into this, for some reason the file path splits like this:

```js
["e", "r", "s", "t", "i", "e", "b", "e", "g", "r", "u", "̈", "ß", "u", "n", "g"]
```

but the string entered into the box splits as:

```js
["e", "r", "s", "t", "i", "e", "b", "e", "g", "r", "ü", "ß", "u", "n", "g"]
```

**Comment by gjtorikian** [comment]
Is there anything I can do here to help contribute? I'm not sure where the splitting occurs. Seems like fuzzaldrin is doing the right thing, but most of the filtering is being handled by `SelectListView`. Is that right?

**Comment by izuzak** [comment]
This also reminds me of https://github.com/atom/atom/issues/1890.

**Comment by jeancroy** [comment]
It looks like the mac file system does that (split ü into u + ¨)

http://stackoverflow.com/questions/5581857/git-and-the-umlaut-problem-on-mac-os-x/5582403#5582403

**Comment by 50Wliu** [comment]
No repro on Windows.  @ungb when you have a chance could you confirm if this bug still exists on macOS?

**Comment by gjtorikian** [comment]
Yes, it does. Fuzzy-finder @ 1.7.3.

![yes_because_no_one_works_on_these](https://user-images.githubusercontent.com/64050/36352571-e91caba4-1488-11e8-8280-bb48e02321c6.gif)
