### ISSUE TITLE
Option to fuzzy-find across projects/windows

### ISSUE THREAD

**Issue by jtokoph** [atom/fuzzy-finder#72]
I like to have multiple related projects open in separate windows. It would be great to be able to open the fuzzy finder in one window/project and still be able to search all open windows/projects.

One reason I prefer to use separate windows per project instead of one combined window is that each project has it's own git repository and I would like all of the fancy git highlighting/colors in my editor.

I'm not sure if the atom API provides a way to look at all workspaces, but I think this would be handy.

**Comment by maxbrunsfeld** [comment]
In the latest Atom release, you can open multiple projects in one window and still get the fancy git highlighting. Right click in the tree view and select 'Add Root Folder' or 'Remove Root Folder'. The fuzzy finder will search all root folders. Does this do what you want?

**Comment by jtokoph** [comment]
Yup, this overall change is an even better solution! Just need to see if I can figure out how to get [project-manager](https://github.com/danielbrodin/atom-project-manager) to work with the new multi-root feature.
