### ISSUE TITLE
No modal-like overlay

### ISSUE THREAD

**Issue by vemv** [atom/fuzzy-finder#74]
Hi,

when I press cmd-t I'd wish just to see the fuzzy-finder itself appearing, not the whole editor being darkened by a modal-like overlay.

The effect is quite tiring to my eyes.

Could you make it optional? Or if there a css which one can override, please let me know.

Thanks!

Victor

**Comment by maxbrunsfeld** [comment]
@vemv what UI theme are you using? The overlay effect will be defined there, via css.

**Comment by vemv** [comment]
I'm using One Light. Unfortunately the overlay is hard to inspect - when I click anything in the Developer Tools, the whole modal goes away.

Basically, making the black, partially-transparent "background" completely transparent instead would solve my issue.

I suspect this isn't a fuzzy-finder specific issue (when I create a file, the same modal is used), sorry for any inconvenience!

**Comment by vemv** [comment]
Hey I finally got it, thanks for pointing out that this was defined in the UI theme.
```
atom-panel.modal { 
    &:after {
      background-color: hsla(0,100%,100%,.0) !important;
    }
}
```
