### ISSUE TITLE
After updating to Atom 0.184.0, fuzzy-finder doesn't find anyting.

### ISSUE THREAD

**Issue by olivier-g** [atom/fuzzy-finder#76]
It keeps re-indexing after every Atom restart, and when it's done I get the following:

![screen shot 2015-02-26 at 11 08 17 am](https://cloud.githubusercontent.com/assets/465250/6395726/f2cc1ea4-bda7-11e4-90cd-6bcec1030442.png)

No files ever get populated in the dropdown, I always see the `indexing project...` message, even after the file count has stopped increasing.

EDIT: It seems this is only happening for this one project. Any ideas if a specific type of file would be causing this issue?

EDIT: Atom 0.184.0, OS X 10.10.2

**Comment by donutmonger** [comment]
I am having a similar problem for only one of my projects where fuzzy finder says "Project is empty."   
![screen shot 2015-02-26 at 2 18 29 pm](https://cloud.githubusercontent.com/assets/3676616/6402106/5efb3fc8-bdc2-11e4-9acf-9f98b18d6fce.png)

**Comment by maxbrunsfeld** [comment]
@donutmonger can you open a separate issue for that? In it, you should report your Atom version and OS.

**Comment by MattKunze** [comment]
@donutmonger - I think I was seeing the same issue with the last couple of releases as well. I was launching `atom` from a terminal within my project folder and getting nothing in the file search results. Explicitly specifying the path with `atom .` works around it for now. It also works if I manually add root folders. Let me know if you file a separate issue, I can add some details there

**Comment by donutmonger** [comment]
@maxbrunsfeld @MattKunze I opened a new issue here https://github.com/atom/fuzzy-finder/issues/77

**Comment by johnathanludwig** [comment]
I am also getting this error after upgrading to 1.8.4 from 1.8.2. Im on OSX 10.10.2. It only seems to be affecting my primary project, and my indexing stops count at 1000. I opened a different project and that one still works fine.

**Comment by knovoselic** [comment]
I've just installed Atom for the first time (v0.184.0) on OSX 10.10.2 and had the same issue - it keeps reindexing after each restart and never completes it (in my case it was getting stuck at 700 files).
After a little while I've figured out that it was do to .zeus.sock file in my project root. It seems that fuzzy search doesn't like sockets. After I've added that file to ignored names list, it has started working properly.

**Comment by johnathanludwig** [comment]
@knovoselic Good call! I had `config/puma.socket` in my project, removing it fixed the issue.

**Comment by maxbrunsfeld** [comment]
This will be fixed in Atom 0.185. Thanks for the report!

**Comment by Trudko** [comment]
Not sure if this is related @maxbrunsfeld but every time I open project (using Project manager package) and then open fuzzy finder , whole project is reindexed. Reindexing is successful, but  I wouldn't expect fuzzy finder to reindex every time I open the project.

**Comment by maxbrunsfeld** [comment]
@Trudko you should open a separate issue for this. Also, please report your Atom version, and whether or not this happens when you open Atom with `atom --safe`.
