### ISSUE TITLE
gitignore patterns are being applied to full paths instead of project-relative paths

### ISSUE THREAD

**Issue by viddo** [atom/fuzzy-finder#79]
Follow-up from last comments in [#77](https://github.com/atom/fuzzy-finder/issues/77#issuecomment-77258901):

I've removed my `~/.atom` directory to rule out any non-default packages or config settings being the cause. I've narrowed it down to this minimal setup to reproduce it:

```bash
mkdir test
cd test
git init
echo "src" > .gitignore
echo "a test file" > test.txt
atom .
```

`cmd-t` yields "Project is empty:
![screen shot 2015-03-04 at 23 11 27](https://cloud.githubusercontent.com/assets/978461/6494753/6ca4eece-c2c4-11e4-8507-390da34c121a.png)

A peculiar detail I've noticed is that it seems to be the word _src_ in the .gitignore file that seems to cause this, and only if edited outside atom (e.g. through vim, or echo like above) or if atom is restarted. Have not found any other word(s) that cause this while fiddling around.

Disabling "Exclude VCS Ignored Paths" or remove/change the word "src" to something else in the .gitignore file makes it work as expected:
![screen shot 2015-03-04 at 23 28 38](https://cloud.githubusercontent.com/assets/978461/6494981/36c3ea38-c2c6-11e4-8cf8-194efbbc7f8a.png)

I use latest versions of Atom (0.186.0) and Mac OSX (Yosemite, 10.10.2).

**Comment by viddo** [comment]
@maxbrunsfeld hope this helps :)

**Comment by bohlander** [comment]
Fwiw, I ran into the same issue with this .gitignore. 

# Compiled Object files, Static and Dynamic libs (Shared Objects)
*.o
*.a
*.so

# Folders
_obj
_test

dispatcher
dynamodb_local*

# emacs
.\#*
\#*\#

dispatcher.test

**Comment by bfagundez** [comment]
same here, a totally different .gitignore

**Comment by graygilmore** [comment]
This isn't exactly the same, but it's related so I'm commenting here. Let me know if this should be a whole new issue.

I'm working on a project that has a *parent* folder that is ignored (both globally and in the parent project). Unfortunately, Atom is looking outside of the scope of the current project.

The structure looks like this

```
- parent_project
  - vendor
    - bundle **ignored folder**
      - gems
        - project **unable to index**
```

Disabling `Exclude VCS Ignored Paths` fixes the issue but isn't ideal. If I open `project` in its own window I expect it to be treated as its own thing.

**Comment by matthewwithanm** [comment]
I'm having the same issue. It seems to be caused by having "*.com" in my gitignore.

**Comment by maxbrunsfeld** [comment]
/cc @izuzak - I haven't been able to repro this yet (I tried using @viddo's steps but it works as expected for me). Could you :eyes: this one?

@viddo is there a `.gitignore` in any parent folder of your project? Or do you have any global `.gitignore` configured in your `~/.gitconfig`?

**Comment by matthewwithanm** [comment]
Oh, I think I see what's happening with me. `load-paths-handler.coffee` is checking against the entire path. In my case, `*.com` is problematic *because my project is in a folder with ".com" in the name*. In other words, my project looks like this:

```
path/
  to/
    awesomesite.com/
      project/
        .gitignore
        index.html
```

Even though "awesomesite.com" isn't part of the project, the path "path/to/awesomesite.com/project" matches ".com", so it gets ignored.

@viddo Do you have "src" somewhere higher up in the path of your minimal test?

**Comment by viddo** [comment]
Indeed I do:
```bash
$ pwd
/Users/viddo/src/test
```

**Comment by viddo** [comment]
@maxbrunsfeld yes, both actually

**Comment by maxbrunsfeld** [comment]
@viddo I updated the title now that we've discovered the exact problem. Thanks a lot for investigating this @graygilmore, @matthewwithanm, @viddo.

**Comment by matthewwithanm** [comment]
:thumbsup: Thanks!

**Comment by viddo** [comment]
:cake:

**Comment by maxbrunsfeld** [comment]
Thanks helping catch this everyone. The fix is on Atom master and we should be releasing again in a few days.

**Comment by kesavanm** [comment]
Pattern to ignore System-generated files **`**/*\?*`** inside the **`.gitignore`** prevents the project from getting Indexed. Removing (or commenting)  this line bring back the Fuzzy finder functionality
