### ISSUE TITLE
"Project is empty" if opening atom in a symlink

### ISSUE THREAD

**Issue by peterbe** [atom/fuzzy-finder#87]
As described in https://discuss.atom.io/t/fuzzy-finder-not-working/15380/11

If you open atom from within a symlinked directory it finds nothing in the fuzzy-finder.

**Comment by MattKunze** [comment]
dup of #77?

**Comment by peterbe** [comment]
Doubt it. My brain has Friday'ed already. :)

#77  is closed but I can still reproduce this easily in 0.187.0.

**Comment by 50Wliu** [comment]
@peterbe do you have the `Follow symlinks` option enabled?

**Comment by peterbe** [comment]
@50Wliu what's that?

**Comment by 50Wliu** [comment]
It's one of the options in Preferences (<kbd>Ctrl+,</kbd> or <kbd>Cmd+,</kbd> if on Mac).

**Comment by peterbe** [comment]
Didn't help. 
![screenshot 2015-03-16 09 08 48](https://cloud.githubusercontent.com/assets/26739/6670490/1b74d23e-cbbc-11e4-9cdd-228af9761db7.png)
What you can see in the screenshot is that I've just opened `atom` inside a symlinked directory and the "Follow symlinks" option is ("was" in fact) on and after Meta-t it still says "Project is empty". 

Note in the header how it says `/Users/peterbe/airmozilla` which is a symlinked directory.

**Comment by philsturgeon** [comment]
Yeah I'm getting this too. Let me know if I can help.

**Comment by atroutt** [comment]
I had this issue today suddenly, I opened my project from a symlinked directory (the root of the project is a symlinked dir) and in the fuzzy finder it said project is empty. But, for me, "Follow Symlinks" was off. I turned it on and that fixed the issue for me. I have atom version 0.187.0

**Comment by peterbe** [comment]
> But, for me, "Follow Symlinks" was off. I turned it on and that fixed the issue for me.

That didn't work for me. I discovered my problem before I even noticed that "Follow symlinks" had been switch on all along. It hadn't helped.

**Comment by zachmullen** [comment]
I have the same problem and figured out how to fix it. It's not to do with symlinks in my case.

I have the following folder structure:

```
repo A
    plugins (a directory containing plugins)
        .gitignore
        repo B
```

Both repo A and repo B are git repositories. The repo B directory is actually ignored by the .gitignore file shown in repo A/plugins. When I opened repo B in atom, I got the "project is empty" message no matter what I did. When I moved repo B out from underneath repo A to a different directory, I restarted atom and fuzzy finder worked again. I haven't looked at the code so I'm not sure, but I suspect the plugin might be looking up too far (i.e. outside of the current project repo) when testing .gitignores.

**Comment by wkonkel** [comment]
:+1:

I get also get "Project is empty" in fuzzy finder when opening a symlink'ed project but not when opening the actual path. Problem still exists regardless of "Follow symlinks" and "Exclude VCS Ignored Paths" settings.

**Comment by Pizzicato** [comment]
same problem here...

**Comment by OmarIthawi** [comment]
Same problem here with `v0.192.0`. Ubuntu 14.04 64bit.
No symlinks in the directory. Everything else is default.

**Comment by stevus** [comment]
On a Mac, turned off (which were on by default) 'Exclude VCS Ignored Paths' & Follow Symlinks. Fuzzy finder worked as expected. Using 0.192.0

**Comment by Pizzicato** [comment]
On Linux is working now, using 0.194.0

**Comment by jdforrester** [comment]
Confirming still not working on Mac when excluding VCS ignored paths, using 0.194.0.

**Comment by Tutorgaming** [comment]
Me not working either .

**Comment by gerrywastaken** [comment]
:+1: There are many symlink issues in Atom: https://discuss.atom.io/t/symbolic-link-directory-git-highlight-issue-and-other-issue-on-atom-shell-command/3324/4

**Comment by victorlcampos** [comment]
+1

**Comment by doggan** [comment]
:+1: Still an issue (Atom 0.210.0 on Mac OS X).

Would love for this to get fixed or for a work-around (other than not using symlinks). Symlinking is especially useful when dealing with multiple versions of server code.

**Comment by ryanmclaughlin** [comment]
:+1: Still an issue

**Comment by mpkostek** [comment]
I am still having this issue.

**Comment by 50Wliu** [comment]
@mpkostek The fix has not been released yet.  After you upgrade to Atom 1.7.0 (when it's released), if you're still having this issue, then please comment here.

**Comment by Trilunaire** [comment]
Still having this issue for me, with symlinked file. I have atom 1.7.3 on Debian Jessie (8).
Atom can't research things in project search and the fuzzy finder stuck at indexing. 
If I delete the linked files it work.
The different file used are linked to /usr/share/automake-1.14.
Even if I run atom as root, it still not working

**Comment by nickkhall** [comment]
same issue. I'm running Ubuntu 16.04, and I'm running Atom 1.10.2.

**Comment by 50Wliu** [comment]
@nickkhall Can you please create a new issue and provide as much relevant information as you can?  See [How Do I Submit A (Good) Bug Report?](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) for some ideas of what you should include in your issue.

**Comment by svanschalkwyk** [comment]
Same here. Symlinked dirs not showing up in tree view. Ugh, back to Kate...

**Comment by omijh** [comment]
The "Exclude VCS Ignored Paths" disabling that setting in preferences fixed the fuzzy finder for me, I guess there was some issue with the ".gitignore" file.
