### ISSUE TITLE
Cmd-p index finds wrong file

### ISSUE THREAD

**Issue by izuzak** [atom/fuzzy-finder#99]
_From @davidthewatson on May 1, 2015 19:51_

I am using Atom 0.194.0 on Mac OS X 10.10.

I open a project directory. I then type Cmd-p and type,

    settings.ini

However, the selected file in the index is:

    settings.template

If I then press enter, the wrong file is loaded.

_Copied from original issue: atom/atom#6603_

**Comment by izuzak** [comment]
@davidthewatson Strange -- I'm having trouble reproducing this, see GIF below.

![settings](https://cloud.githubusercontent.com/assets/38924/7436361/4d9910c6-f04d-11e4-861c-7ea24a321c4d.gif)

Do you see the same behavior in the latest version of Atom (0.196.0) and in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, can you share a link to an example project (e.g. on GitHub) with which you are reproducing this so that we can take a look?

**Comment by lee-dohm** [comment]
@izuzak I was able to *kind of* reproduce the issue when I placed `settings.template` in the root of the project and `settings.ini` in a directory a couple levels down **and only typed "settings" into the box**. But if they were at the same level in the directory structure then `settings.ini` came up first.

Could be the source of some confusion?

![screen shot 2015-05-01 at 1 02 32 pm](https://cloud.githubusercontent.com/assets/1038121/7436426/7726fafc-f002-11e4-8758-3f773c37dced.png)

1. Open Atom
1. Open a project
1. Create and save a file at `settings.template`
1. Create and save a file at `foo/bar/settings.ini`
1. Close both files
1. Open the fuzzy-finder by pressing <kbd>Cmd+P</kbd>
1. Type in "settings"

**Comment by izuzak** [comment]
@lee-dohm Yeah, that might be confusing but not sure it's the problem @davidthewatson is reporting. Looking at the issue report, I see this:

> I open a project directory. I then type Cmd-p and type,

> `settings.ini`

@davidthewatson what exactly did you type into the input box? `settings.ini` or just `settings`?

**Comment by MrTact** [comment]
I have been running into something similar to this myself. For example, I have a large-ish project in which I was searching for a file called ResourceConstants.java. Typing "res" got me a file called "requirements.yml." Only if I typed the entire filename would the fuzzy finder correctly pick the java file (and I think it wouldn't even show up in the list, in fact). However, creating a test project with just those two files in it worked as expected. In another case, on a similar project, a file called "OrganizationView.java" required typing "OrganizationView.ja" before it showed up in the list.

This is on 1.0.5 on Mac OS X Yosemite, and it happens with or without safe mode enabled.

**Comment by izuzak** [comment]
I'm going to close this since we weren't able to reproduce this and didn't heard back from @davidthewatson. 

The other problems described in this thread seem to be related with how fuzzy finder scores matches, not with fuzzy finder selecting a file which should never be selected. There are other issues open on this package and on https://github.com/atom/fuzzaldrin which discuss such problems.

@davidthewatson -- if you can still reproduce this, we'd appreciate it if you could share more specific steps to reproduce, and a GIF which demonstrates the problem. :v:
